"""add data

Revision ID: 34e81d30be4d
Revises: e033ced1e9b5
Create Date: 2022-12-22 20:59:30.269823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e81d30be4d'
down_revision = 'e033ced1e9b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
