"""add orm relation

Revision ID: 50b576e6a48e
Revises: 34e81d30be4d
Create Date: 2022-12-22 21:00:26.965587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b576e6a48e'
down_revision = '34e81d30be4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
